#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-ellipsis
Version  : 0.3.2
Release  : 46
URL      : https://cran.r-project.org/src/contrib/ellipsis_0.3.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ellipsis_0.3.2.tar.gz
Summary  : Tools for Working with ...
Group    : Development/Tools
License  : MIT
Requires: R-ellipsis-lib = %{version}-%{release}
Requires: R-rlang
BuildRequires : R-rlang
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# ellipsis
<!-- badges: start -->
[![Lifecycle:
maturing](https://img.shields.io/badge/lifecycle-maturing-blue.svg)](https://lifecycle.r-lib.org/articles/stages.html)
[![CRAN
status](https://www.r-pkg.org/badges/version/ellipsis)](https://cran.r-project.org/package=ellipsis)
[![Travis build
status](https://travis-ci.org/r-lib/ellipsis.svg?branch=master)](https://travis-ci.org/r-lib/ellipsis)
[![Codecov test
coverage](https://codecov.io/gh/r-lib/ellipsis/branch/master/graph/badge.svg)](https://codecov.io/gh/r-lib/ellipsis?branch=master)
<!-- badges: end -->

%package lib
Summary: lib components for the R-ellipsis package.
Group: Libraries

%description lib
lib components for the R-ellipsis package.


%prep
%setup -q -n ellipsis
pushd ..
cp -a ellipsis buildavx2
popd
pushd ..
cp -a ellipsis buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737140127

%install
export SOURCE_DATE_EPOCH=1737140127
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ellipsis/DESCRIPTION
/usr/lib64/R/library/ellipsis/INDEX
/usr/lib64/R/library/ellipsis/LICENSE
/usr/lib64/R/library/ellipsis/Meta/Rd.rds
/usr/lib64/R/library/ellipsis/Meta/features.rds
/usr/lib64/R/library/ellipsis/Meta/hsearch.rds
/usr/lib64/R/library/ellipsis/Meta/links.rds
/usr/lib64/R/library/ellipsis/Meta/nsInfo.rds
/usr/lib64/R/library/ellipsis/Meta/package.rds
/usr/lib64/R/library/ellipsis/NAMESPACE
/usr/lib64/R/library/ellipsis/NEWS.md
/usr/lib64/R/library/ellipsis/R/ellipsis
/usr/lib64/R/library/ellipsis/R/ellipsis.rdb
/usr/lib64/R/library/ellipsis/R/ellipsis.rdx
/usr/lib64/R/library/ellipsis/help/AnIndex
/usr/lib64/R/library/ellipsis/help/aliases.rds
/usr/lib64/R/library/ellipsis/help/ellipsis.rdb
/usr/lib64/R/library/ellipsis/help/ellipsis.rdx
/usr/lib64/R/library/ellipsis/help/paths.rds
/usr/lib64/R/library/ellipsis/html/00Index.html
/usr/lib64/R/library/ellipsis/html/R.css
/usr/lib64/R/library/ellipsis/tests/testthat.R
/usr/lib64/R/library/ellipsis/tests/testthat/test-check.R
/usr/lib64/R/library/ellipsis/tests/testthat/test-dots.R
/usr/lib64/R/library/ellipsis/tests/testthat/test-safe.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/ellipsis/libs/ellipsis.so
/V4/usr/lib64/R/library/ellipsis/libs/ellipsis.so
/usr/lib64/R/library/ellipsis/libs/ellipsis.so
